version: '3.8'

volumes:
  lemur_certs:
    external: true

services:
  frontend:
    build:
      dockerfile: Dockerfile-frontend
      context: .
    volumes:
      - type: bind
        source: ./lemur/lemur/static
        target: /app/lemur/static
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - backend
    command: npx gulp serve
    ports:
      - "3000:3000"
      - "3001:3001"

  backend:
    build:
      dockerfile: Dockerfile-backend
      context: .
    volumes:
      # mapping only lemur directory to avoid overwriting some files
      # that result in lemur package not being fully installed
      - type: bind
        source: ./lemur/lemur
        target: /app/lemur
        read_only: false
        consistency: delegated
        volume:
          nocopy: true
      - type: bind
        source: ./lemur-ejbca-plugin/lemur_ejbca
        target: /app/lemur/plugins/lemur_ejbca
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: lemur_certs
        target: /usr/local/share/certs
        read_only: true
        volume:
          nocopy: true
    links:
      - postgres
    depends_on:
      - postgres
      - redis
    command: lemur runserver -r -d --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: lemur
      POSTGRES_PASSWORD: lemur
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
