## Build step
FROM python:3.7 as build

RUN apt-get update \
    && apt-get install -y libldap2-dev libsasl2-dev

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app

COPY lemur/requirements*.txt ./
COPY lemur-ejbca-plugin/requirements.txt ./requirements-ejbca-plugin.txt

RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt
RUN pip install -r requirements-docs.txt
RUN pip install -r requirements-tests.txt
RUN pip install -r requirements-ejbca-plugin.txt

## Main
FROM build as backend

RUN mkdir /root/.lemur
COPY lemur.conf.py /root/.lemur/lemur.conf.py
COPY lemur /app/

# Install ejbca plugin
COPY lemur-ejbca-plugin/lemur_ejbca /app/lemur/plugins/lemur_ejbca
COPY lemur-setup.py /app/setup.py

RUN pip install -e .